### PR TITLE
Add Google Analytics and PACE.js options

### PR DESCRIPTION
**Pull request by matuu**
Also updated base_helper.html

### CODE REVIEW

**Comment by Aeyoun** [comment]
`ANALYTICS` is a no-go. `BODY_END` already fulfills this purpose and is documented as such in `conf.py` and this new setting adds no advantages over that.

**Comment by matuu** [comment]
It recommend placing the snippet at the end of the <head> section for best performance. BODY_END places the snippet at the end of the body section. See https://support.google.com/analytics/answer/1008080?hl=en#GA

Directly from Google:

> One of the main advantages of the asynchronous snippet is that you can position it at the top of the HTML document. This increases the likelihood that the tracking beacon will be sent before the user leaves the page. It is customary to place JavaScript code in the `head` section, and we recommend placing the snippet at the bottom of the section for best performance.

**Comment by ralsina** [comment]
@matuu then you can add it in EXTRA_HEAD_DATA :-)

**Comment by matuu** [comment]
Ok, I like that. I'll fix it

**Pull request closed without merging**
