### PR TITLE
Metadata

### PR DESCRIPTION
**Pull request by ralsina**
Quick minimal metadata addition. Please review carefully, I am not sure what I'm doing.

Building the site currently fails on reveal at least.

### CODE REVIEW

**Comment by Kwpolska** [comment]
This is a good first attempt, but attribution and licensing (and perhaps tags) still needs to be done:

* attribution for adapted themes (eg. lanyon) `based_on = Bootstrap 3 <https://getbootstrap.com/>`
* licenses: if we don’t have a license specified, it’s safer to say `unknown`
* author: *Roberto Alsina* or other names will work better in many of those themes

**Comment by ralsina** [comment]
For those I wrote, I don't mind. For the others, yes, we have to look at each one. At least now the files would be in place.

**Comment by Kwpolska** [comment]
Well, I do mind you not being attributed. Since we still support the old files, no need to rush.

**Comment by ralsina** [comment]
I already get more credit than I deserve, mostly for stuff you did ;-)

**Comment by Kwpolska** [comment]
Finished this. I don’t have time to track down submodule themes, I’ll get to it someday.

**Pull request merged**
