### PR TITLE
feat: add willy-theme

### PR DESCRIPTION
**Pull request by Woile**
# Willy theme

This is a modern theme, CSS and mobile first.

Built using TailwindCSS.

This is a one of snapshot of the repo where I maintain the [willy-theme](https://github.com/Woile/willy-theme).
It's feature complete AFAIK. I mention this because my original theme may take a different path in the future, but I 
wanted to give back to this awesome tool!

I'm using it on my website: https://woile.dev/blog/

## Features

- Use of semantic elements
- Night/light mode
- 99% CSS (JS used to persist night mode preferences)
- Mobile support
- Colors and contrast ratio for readability compliant with WCAG 2.0

### CODE REVIEW

**Comment by Kwpolska** [comment]
Nice theme! Are you sure about your license choice though? Is AGPL appropriate for a theme used on someone’s website? What would the effects be for someone who installs this theme, what do you expect them to do?

**Comment by Woile** [comment]
I think so, it's available for commercial use, it just requires that the
source is shared back if used to provide a service over a network.
Copyright and license notices must be preserved, in this case I haven't
placed a copyright and the license should be agpl as well.

Which points are you concerned?

Regards!

**Comment by Kwpolska** [comment]
First, note that I’m not a lawyer.

The [AGPL](https://www.gnu.org/licenses/agpl-3.0.html) says this:

> 4\. Conveying Verbatim Copies.
>
> You may convey verbatim copies of the Program's source code as you receive it, in any medium, provided that you conspicuously and appropriately publish on each copy an appropriate copyright notice; keep intact all notices stating that this License and any non-permissive terms added in accord with section 7 apply to the code; keep intact all notices of the absence of any warranty; and give all recipients a copy of this License along with the Program.

From this, as well the “publish source even if over network” clause, I interpret this as requiring every user to (a) add a copyright notice for the theme to their pages, and (b) share the source code of the theme, including any modifications of theirs.

**Comment by Woile** [comment]
Which LICENSE would you recommend? I wanted to let people use it even for commercial use, but the source should be available and the code should be contributed back to us in order to improve it.
My understand was that AGPL 3 was for that use case.

What about GNU GPLv3?

**Comment by Kwpolska** [comment]
GPLv3 is fine IMO. Nikola users would probably contribute changes if they would be useful for others anyway.

**Comment by Woile** [comment]
That's it, I've updated to GPLv3 :smiley:

**Comment by Woile** [comment]
Cool, thanks a lot! sorry for the `.theme` :+1:

**Pull request merged**
