### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### getnikola/nikola-themes now has a Chat Room on Gitter

@hhirsch has just created a chat room. You can visit it here: [https://gitter.im/getnikola/nikola-themes](https://gitter.im/getnikola/nikola-themes?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/getnikola/nikola-themes?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by Kwpolska** [comment]
Fuck that.  We have IRC.

**Comment by hhirsch** [comment]
@Kwpolska I clicked it by accident when I added another project to gitter.

**Comment by Kwpolska** [comment]
@hhirsch okay. Could you please delete the room, if that’s possible?

**Comment by hhirsch** [comment]
@Kwpolska Yes. I'll do it this evening.

**Comment by Kwpolska** [comment]
@hhirsch thanks!

**Pull request closed without merging**
