### PR TITLE
[zen] Usage of ForkAwesome icon fonts instead of FontAwesome

### PR DESCRIPTION
**Pull request by encarsia**
I modified the zen theme to use icons from the [ForkAwesome](https://forkawesome.github.io) project instead of the originally used [FontAwesome](http://fontawesome.io) icons which is in active development and contains more icons.

Currently FontAwesome v.3.2.1 is still used which has been deprecated for a while now.

### CODE REVIEW

**Comment by Kwpolska** [comment]
What's wrong with Font Awesome 5? (Also, any changes need to be migrated to
zen-jinja.)

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by encarsia** [comment]
> What's wrong with Font Awesome 5?
Nothing, I guess. But Fork Awesome has Mastodon and other FLOSS related icons Font Awesome hasn't.

> Also, any changes need to be migrated to zen-jinja.
Okay.

Regards
Anke

**Comment by ralsina** [comment]
Why not make it a separate theme instead?

**Comment by Kwpolska** [comment]
`zen` could be upgraded to fontawesome v4. A v5 upgrade could also be done, but that one requires updating font references (eg. `fab fa-twitter` because Twitter is now in the “brand” icon set)

**Comment by ralsina** [comment]
+1 to making a zen fork and to upgrading zen to FA v4 (but not really important)

**Comment by encarsia** [comment]
> `zen` could be upgraded to fontawesome v4

Since ForkAwesome is a FA 4.7 fork and going with FA 4.7 on my personal site this is doable. It appears logical to start with this task first before creating the zen fork to achieve my initial request.

**Pull request closed without merging**
