### PR TITLE
Material-theme - More options for customization

### PR DESCRIPTION
**Pull request by matuu**

### CODE REVIEW

**Comment by ralsina** [comment]
Sice this is your theme, do you want commit rights to just commit directly?

**Comment by Kwpolska** [comment]
(Don’t forget that we need to push the updates to the server manually.)

**Comment by ralsina** [comment]
Oh yes, we do.

**Comment by ralsina** [comment]
ghostjs does work well enough now, I really should automate this somewhere.

**Comment by Kwpolska** [comment]
In the meantime, I (and my superior font configuration) will rebuild it now.

**Comment by matuu** [comment]
Ok, I promise to keep the theme updated and running.

Right now, images not shown in https://themes.getnikola.com/#material-theme. I´ll try to fix him today.

**Pull request merged**
