### PR TITLE
Add new theme based on Bootstrap 3 using Google Material Design.

### PR DESCRIPTION
**Pull request by matuu**
Repo: https://github.com/matuu/material-theme-nikola

### CODE REVIEW

**Comment by Kwpolska** [comment]
Looks great! Your demo has issues with the Raleway font though, mind looking into that?

**Comment by matuu** [comment]
I don't find problem with font into demo site. You prefer to use a hosted version?

**Comment by Kwpolska** [comment]
Uninstall Raleway from your system, it will display Times New Roman.  At least it did for me on a clean Windows 10 install.

**Comment by matuu** [comment]
I haven't installed Raleway font in my system. It is downloaded from fonts.googleapis.com.
I'll try use a hosted version of font.

**Comment by matuu** [comment]
Done. The Raleway font is included into assets folder.

**Comment by Kwpolska** [comment]
Hopefully it will work better.

Thanks for your contribution! I’ll build the themes site in a while.

**Comment by Kwpolska** [comment]
Your theme is now available on [themes.getnikola.com](https://themes.getnikola.com/#material-theme). I changed the readme a bit (we have our own theme demos).

**Pull request merged**
