### PR TITLE
Add jidn theme

### PR DESCRIPTION
**Pull request by jidn**
Based on the Lanyon theme and inspired by a blog with author information
at post end.  See more at [jidn/nikola-jidn](https://github.com/jidn/nikola-jidn)

There is a demo post using this theme, and describing the settings, at
http://jidn.com/blog/jidn-a-nikola-theme/

### CODE REVIEW

**Comment by ralsina** [comment]
Nice!!!!

**Comment by ralsina** [comment]
It will appear in the site at some point in the future :-)

**Comment by Kwpolska** [comment]
The theme’s great, but perhaps you could commit your files directly to this repo, as opposed to using a submodule? That would make it easier for us to maintain it, and you’ll of course get commit rights to this repository.

**Comment by jidn** [comment]
How do you want me to proceed?  Create a branch, replace the submodule, alter the .gitmodules, and submit a pull request?

**Comment by Kwpolska** [comment]
Yes. Make sure the submodule is forgotten by git (`git rm`; deinit should do it too)

**Pull request merged**
